import type { PoolClient } from 'pg';
import type { TenantId,UserId } from '../../kernel/ids/index.ts';
import type { CreateQuoteTemplate,QuoteTemplateDto,QuoteTemplatesOverview,UpdateQuoteTemplate } from '../../modules/quote-templates/api/contracts.ts';
import { QuoteTemplateRejectedError,type QuoteTemplatesRepository } from '../../modules/quote-templates/application/quote-templates-repository.ts';
import type { PostgresTransactionRunner } from './transaction-runner.ts';

type TemplateRow=Record<string,unknown>;
const COLUMNS='id,name,style,company_name,address,postal_code,city,country,phone,email,website,siret,tva_number,logo_url,brand_color,accent_color,font_family,validity_days,footer_text';
const MUTABLE=['name','style','company_name','address','postal_code','city','country','phone','email','website','siret','tva_number','logo_url','brand_color','accent_color','font_family','validity_days','footer_text'] as const;

export class PostgresQuoteTemplatesRepository implements QuoteTemplatesRepository{
  constructor(private readonly tx:PostgresTransactionRunner){}
  overview(actor:UserId,tenantId:string):Promise<QuoteTemplatesOverview>{return this.run(actor,tenantId,async c=>{const [templates,preference]=await Promise.all([c.query<TemplateRow>(`select ${COLUMNS} from public.quote_templates where tenant_id=$1 order by created_at,id`,[tenantId]),c.query<{default_quote_template_id:string|null}>('select default_quote_template_id from public.user_preferences where user_id=$1',[actor])]);return{templates:templates.rows.map(dto),defaultTemplateId:preference.rows[0]?.default_quote_template_id??null};});}
  create(actor:UserId,tenantId:string,input:CreateQuoteTemplate):Promise<QuoteTemplateDto>{return this.run(actor,tenantId,async c=>{const entries=MUTABLE.flatMap(key=>input[key]===undefined?[]:[[key,input[key]] as const]);return dto((await c.query<TemplateRow>(`insert into public.quote_templates(tenant_id,user_id,${entries.map(([key])=>key).join(',')}) values($1,$2,${entries.map((_,index)=>`$${index+3}`).join(',')}) returning ${COLUMNS}`,[tenantId,actor,...entries.map(([,value])=>value)])).rows[0]!);});}
  update(actor:UserId,tenantId:string,id:string,input:UpdateQuoteTemplate):Promise<void>{return this.run(actor,tenantId,async c=>{const entries=Object.entries(input).filter(([,value])=>value!==undefined);if(entries.length===0)throw invalid('Une modification est requise.');const result=await c.query(`update public.quote_templates set ${entries.map(([key],index)=>`${key}=$${index+3}`).join(',')},updated_at=clock_timestamp() where tenant_id=$1 and id=$2`,[tenantId,id,...entries.map(([,value])=>value)]);if(result.rowCount!==1)throw notFound();});}
  remove(actor:UserId,tenantId:string,id:string):Promise<void>{return this.run(actor,tenantId,async c=>{if((await c.query('delete from public.quote_templates where tenant_id=$1 and id=$2',[tenantId,id])).rowCount!==1)throw notFound();await c.query('update public.user_preferences set default_quote_template_id=null,updated_at=clock_timestamp() where user_id=$1 and default_quote_template_id=$2',[actor,id]);});}
  setDefault(actor:UserId,tenantId:string,id:string|null):Promise<void>{return this.run(actor,tenantId,async c=>{if(id!==null&&!id.startsWith('builtin-')&&!(await c.query('select 1 from public.quote_templates where tenant_id=$1 and id=$2',[tenantId,id])).rowCount)throw notFound();await c.query(`insert into public.user_preferences(user_id,default_quote_template_id) values($1,$2) on conflict(user_id) do update set default_quote_template_id=excluded.default_quote_template_id,updated_at=clock_timestamp()`,[actor,id]);});}
  private async run<T>(actor:UserId,tenantId:string,operation:(client:PoolClient)=>Promise<T>):Promise<T>{try{return await this.tx.run({userId:actor,tenantId:tenantId as TenantId},operation);}catch(error){if(error instanceof QuoteTemplateRejectedError)throw error;const value=error as {code?:string;message?:string};if(value.code==='23502'||value.code==='23514'||value.code==='22001')throw invalid(value.message??'Gabarit invalide.');throw new QuoteTemplateRejectedError('permission_denied',value.message??String(error));}}
}
function dto(row:TemplateRow):QuoteTemplateDto{return{id:String(row['id']),builtin:false,name:String(row['name']),style:row['style']==='classique'||row['style']==='atelier'||row['style']==='corporate'?row['style']:'custom',company_name:nullable(row['company_name']),address:nullable(row['address']),postal_code:nullable(row['postal_code']),city:nullable(row['city']),country:nullable(row['country']),phone:nullable(row['phone']),email:nullable(row['email']),website:nullable(row['website']),siret:nullable(row['siret']),tva_number:nullable(row['tva_number']),logo_url:nullable(row['logo_url']),brand_color:nullable(row['brand_color']),accent_color:nullable(row['accent_color']),font_family:nullable(row['font_family']),validity_days:row['validity_days']===null?null:Number(row['validity_days']),footer_text:nullable(row['footer_text'])};}
function nullable(value:unknown){return value===null?null:String(value);}
function invalid(message:string){return new QuoteTemplateRejectedError('invalid_template',message);}
function notFound(){return new QuoteTemplateRejectedError('not_found','Gabarit introuvable.');}
