import type { PoolClient } from 'pg';
import type { TenantId, UserId } from '../../kernel/ids/index.ts';
import { toIsoTimestampOrNull } from '../../modules/_shared/application/index.ts';
import type { RoleCatalogDefinition, RolesCatalog, RolesOverview, SaveRoleDefinitionCommand, SetRoleAssignmentResult, UserAccessProfile, UserRolesDetail } from '../../modules/roles/api/contracts.ts';
import { RoleRejectedError, type RolesRepository } from '../../modules/roles/application/roles-repository.ts';
import type { PostgresTransactionRunner } from './transaction-runner.ts';

type Row = Record<string, unknown>;
export class PostgresRolesRepository implements RolesRepository {
  constructor(private readonly tx: PostgresTransactionRunner) {}
  userCapability(actor: UserId, tenantId: string, capability: string): Promise<boolean> {
    return this.tx.run({tenantId:tenantId as TenantId,userId:actor},async c=>(await c.query<{v:boolean}>('select magrit.actor_has_capability($1,$2) v',[tenantId,capability])).rows[0]?.v===true);
  }
  accessProfile(actor: UserId, tenantId: string): Promise<UserAccessProfile> { return this.tx.run({tenantId:tenantId as TenantId,userId:actor},async c=>{
    const m=await member(c,tenantId,actor); const admin=isAdmin(String(m['role'])); const caps=admin?[]:await capabilities(c,tenantId,actor);
    return {tenantId,userId:actor,membership:admin?'admin':'member',isAdmin:admin,surfaces:admin?['workspace','backoffice']:['workspace'],capabilities:caps};
  }); }
  overview(actor: UserId, tenantId: string): Promise<RolesOverview> { return this.tx.run({tenantId:tenantId as TenantId,userId:actor},async c=>{await requireAdmin(c,tenantId,actor);const definitions=await roles(c,tenantId,false);return {roles:definitions.map(summary),members:await members(c,tenantId),assignments:await assignments(c,definitions.map(r=>String(r['id'])))};}); }
  catalog(actor: UserId, tenantId: string): Promise<RolesCatalog> { return this.tx.run({tenantId:tenantId as TenantId,userId:actor},async c=>{await requireAdmin(c,tenantId,actor);const rs=await roles(c,tenantId,true);return {roles:rs.map(catalog),members:await members(c,tenantId),assignments:await assignments(c,rs.map(r=>String(r['id'])))};}); }
  userDetail(actor: UserId, tenantId: string, userId: string): Promise<UserRolesDetail> { return this.tx.run({tenantId:tenantId as TenantId,userId:actor},async c=>{await requireAdmin(c,tenantId,actor);const m=await member(c,tenantId,userId);const rs=await roles(c,tenantId,false);const shops=(await c.query<{id:string;name:string}>('select id,name from public.shops where tenant_id=$1 and deleted_at is null order by name',[tenantId])).rows;return {roles:rs.map(summary),assignments:(await assignments(c,rs.map(r=>String(r['id'])))).filter(a=>a.userId===userId),shops,accessScope:m.access_scope==='shop_only'?'shop_only':'magrit_full',allowedShopIds:Array.isArray(m.allowed_shop_ids)?m.allowed_shop_ids.map(String):[]};}); }
  setAssignment(actor: UserId, tenantId: string, userId: string, roleId: string, active: boolean): Promise<SetRoleAssignmentResult> { return this.write(actor,tenantId,async c=>{
    await member(c,tenantId,userId);const r=(await c.query<Row>('select id,system_key from public.tenant_role_definitions where tenant_id=$1 and id=$2 and archived_at is null',[tenantId,roleId])).rows[0];if(!r)throw reject('role_not_found','Rôle introuvable.');if(!['option_shops','option_orders'].includes(String(r['system_key'])))throw reject('invalid_definition','Seules les options Boutiques et Commandes sont assignables.');
    const current=(await c.query<{id:string}>('select id from public.tenant_role_assignments where role_definition_id=$1 and user_id=$2 and revoked_at is null for update',[roleId,userId])).rows[0];if(active&&current)return {active:true,assignmentId:current.id};if(!active&&!current)return {active:false,assignmentId:null};if(active){const x=await c.query<{id:string}>('insert into public.tenant_role_assignments(role_definition_id,user_id,assigned_by) values($1,$2,$3) returning id',[roleId,userId,actor]);return {active:true,assignmentId:x.rows[0]!.id};}await c.query('update public.tenant_role_assignments set revoked_at=clock_timestamp(),revoked_by=$2 where id=$1',[current!.id,actor]);return {active:false,assignmentId:null};
  }); }
  createDefinition(actor: UserId, tenantId: string, command: SaveRoleDefinitionCommand): Promise<RoleCatalogDefinition> { return this.write(actor,tenantId,async c=>catalog(await save(c,tenantId,actor,null,command))); }
  updateDefinition(actor: UserId, tenantId: string, roleId: string, command: SaveRoleDefinitionCommand): Promise<RoleCatalogDefinition> { return this.write(actor,tenantId,async c=>catalog(await save(c,tenantId,actor,roleId,command))); }
  archiveDefinition(actor: UserId, tenantId: string, roleId: string): Promise<void> { return this.write(actor,tenantId,async c=>{const r=(await c.query<Row>('select name,system_key from public.tenant_role_definitions where tenant_id=$1 and id=$2 for update',[tenantId,roleId])).rows[0];if(!r)throw reject('role_not_found','Rôle introuvable.');if(r['system_key']!==null||['Owner','Admin','Acheteur','Producteur'].includes(String(r['name'])))throw reject('canonical_role','Un rôle canonique ne peut pas être archivé.');await c.query('update public.tenant_role_definitions set archived_at=clock_timestamp() where id=$1',[roleId]);}); }
  reorderDefinitions(actor: UserId, tenantId: string, first: string, second: string): Promise<void> { return this.write(actor,tenantId,async c=>{const rs=await c.query<{id:string;ordering_index:number}>('select id,ordering_index from public.tenant_role_definitions where tenant_id=$1 and id=any($2::uuid[]) and archived_at is null for update',[tenantId,[first,second]]);if(rs.rowCount!==2)throw reject('role_not_found','Rôle introuvable.');const by=new Map(rs.rows.map(r=>[r.id,r.ordering_index]));await c.query('update public.tenant_role_definitions set ordering_index=case id when $2 then $4::integer when $3 then $5::integer end where tenant_id=$1 and id=any($6::uuid[])',[tenantId,first,second,by.get(second),by.get(first),[first,second]]);}); }
  private write<T>(actor:UserId,tenantId:string,fn:(c:PoolClient)=>Promise<T>):Promise<T>{return this.tx.run({tenantId:tenantId as TenantId,userId:actor},async c=>{try{await requireAdmin(c,tenantId,actor);return await fn(c);}catch(e){if(e instanceof RoleRejectedError)throw e;const x=e as {code?:string;message?:string};if(x.code==='23505')throw reject('definition_conflict','Un rôle portant ce nom existe déjà.');if(x.code==='23514')throw reject('invalid_definition',x.message??'Définition invalide.');throw reject('permission_denied',x.message??String(e));}});}
}
async function save(c:PoolClient,t:string,a:UserId,id:string|null,x:SaveRoleDefinitionCommand){if(x.scope==='shop'&&!(await c.query('select 1 from public.shops where id=$1 and tenant_id=$2 and deleted_at is null',[x.scopeShopId,t])).rowCount)throw reject('invalid_definition','La boutique de portée n appartient pas à cet espace.');const p=[t,x.name,x.description,JSON.stringify(x.capabilities),x.notifyPolicy,x.scope,x.scopeShopId,x.orderingIndex];if(id===null)return (await c.query<Row>('insert into public.tenant_role_definitions(tenant_id,name,description,capabilities,notify_policy,scope,scope_shop_id,ordering_index,created_by) values($1,$2,$3,$4::jsonb,$5,$6,$7,$8,$9) returning *',[...p,a])).rows[0]!;const r=await c.query<Row>('update public.tenant_role_definitions set name=$2,description=$3,capabilities=$4::jsonb,notify_policy=$5,scope=$6,scope_shop_id=$7,ordering_index=$8 where tenant_id=$1 and id=$9 returning *',[...p,id]);if(!r.rows[0])throw reject('role_not_found','Rôle introuvable.');return r.rows[0];}
async function member(c:PoolClient,t:string,u:string){const r=(await c.query<Row>('select role,access_scope,allowed_shop_ids from public.tenant_members where tenant_id=$1 and user_id=$2',[t,u])).rows[0];if(!r)throw reject('member_not_found','Membre introuvable.');return r;}
async function requireAdmin(c:PoolClient,t:string,u:string){const m=await member(c,t,u);if(!isAdmin(String(m['role'])))throw reject('permission_denied','Un administrateur est requis.');}
async function roles(c:PoolClient,t:string,all:boolean){return (await c.query<Row>(`select * from public.tenant_role_definitions where tenant_id=$1 ${all?'':'and archived_at is null'} order by ordering_index,id`,[t])).rows;}
async function members(c:PoolClient,t:string){return (await c.query<Row>('select m.user_id,u.email_normalized email,m.role from public.tenant_members m join public.app_users u on u.id=m.user_id where m.tenant_id=$1 order by u.email_normalized',[t])).rows.map(r=>({userId:String(r['user_id']),email:String(r['email']),legacyRole:String(r['role'])}));}
async function assignments(c:PoolClient,ids:string[]){if(!ids.length)return[];return (await c.query<Row>('select id,role_definition_id,user_id from public.tenant_role_assignments where role_definition_id=any($1::uuid[]) and revoked_at is null',[ids])).rows.map(r=>({id:String(r['id']),roleId:String(r['role_definition_id']),userId:String(r['user_id'])}));}
async function capabilities(c:PoolClient,t:string,u:string){const r=await c.query<{capabilities:Record<string,boolean>}>('select d.capabilities from public.tenant_role_assignments a join public.tenant_role_definitions d on d.id=a.role_definition_id where a.user_id=$1 and d.tenant_id=$2 and a.revoked_at is null and d.archived_at is null',[u,t]);return [...new Set(r.rows.flatMap(x=>Object.entries(x.capabilities).filter(([,v])=>v).map(([k])=>k)))].sort();}
function summary(r:Row){return {id:String(r['id']),name:String(r['name']),description:String(r['description']),capabilities:record(r['capabilities']),orderingIndex:Number(r['ordering_index']),systemKey:r['system_key']===null?null:String(r['system_key'])};}
function catalog(r:Row):RoleCatalogDefinition{return {...summary(r),tenantId:String(r['tenant_id']),notifyPolicy:r['notify_policy'] as RoleCatalogDefinition['notifyPolicy'],scope:r['scope'] as RoleCatalogDefinition['scope'],scopeShopId:r['scope_shop_id']===null?null:String(r['scope_shop_id']),archivedAt:toIsoTimestampOrNull(r['archived_at'] as Date|null)};}
function record(v:unknown):Record<string,boolean>{return v&&typeof v==='object'&&!Array.isArray(v)?Object.fromEntries(Object.entries(v).filter((x):x is [string,boolean]=>typeof x[1]==='boolean')):{};}
function isAdmin(r:string){return r==='owner'||r==='admin';} function reject(code:ConstructorParameters<typeof RoleRejectedError>[0],m:string){return new RoleRejectedError(code,m);}
