import type { PoolClient } from 'pg';
import type { TenantId, UserId } from '../../kernel/ids/index.ts';
import { shopCustomerAccountSchema, type EnsureSelfShopCustomerResult, type ShopCustomerAccount } from '../../modules/shop-customers/api/contracts.ts';
import { ShopCustomerRejectedError, type CreateShopCustomerRecord, type ShopCustomersRepository } from '../../modules/shop-customers/application/shop-customers-repository.ts';
import type { PostgresTransactionRunner } from './transaction-runner.ts';

type Row = Record<string, unknown>;
const COLUMNS = 'id,shop_id,email,normalized_email,full_name,auth_subject_id,status,created_by_magrit_user_id,customer_contact_id,created_at,activated_at,suspended_at';

export class PostgresShopCustomersRepository implements ShopCustomersRepository {
  constructor(private readonly tx: PostgresTransactionRunner) {}

  list(actor: UserId, tenantId: string, shopId: string): Promise<ShopCustomerAccount[]> { return this.read(actor,tenantId,async c=>{await shop(c,tenantId,shopId);return (await c.query<Row>(`select ${COLUMNS} from public.shop_customer_accounts where tenant_id=$1 and shop_id=$2 order by created_at desc,id`,[tenantId,shopId])).rows.map(account);}); }
  findByNormalizedEmail(actor: UserId,tenantId:string,shopId:string,email:string):Promise<ShopCustomerAccount|null>{return this.read(actor,tenantId,async c=>{await shop(c,tenantId,shopId);return maybe((await c.query<Row>(`select ${COLUMNS} from public.shop_customer_accounts where tenant_id=$1 and shop_id=$2 and normalized_email=$3`,[tenantId,shopId,email])).rows[0]);});}
  create(actor:UserId,tenantId:string,shopId:string,record:CreateShopCustomerRecord):Promise<ShopCustomerAccount>{return this.write(actor,tenantId,'can_manage_shop_customers',async c=>{await shop(c,tenantId,shopId);const row=(await c.query<Row>(`insert into public.shop_customer_accounts(tenant_id,shop_id,email,normalized_email,full_name,status,created_by_magrit_user_id,customer_contact_id) values($1,$2,$3,$4,$5,$6,$7,$8) returning ${COLUMNS}`,[tenantId,shopId,record.email,record.normalizedEmail,record.fullName,record.status,record.createdByMagritUserId,record.customerContactId??null])).rows[0]!;return account(row);});}
  ensureSelf(actor:UserId,tenantId:string,shopId:string):Promise<EnsureSelfShopCustomerResult>{return this.write(actor,tenantId,'can_impersonate_shop_customer',async c=>{await shop(c,tenantId,shopId);const user=(await c.query<{email:string;name:string|null}>('select email_normalized email,display_name name from public.app_users where id=$1',[actor])).rows[0];if(!user)throw reject('permission_denied','Identité Magrit introuvable.');const existing=(await c.query<Row>(`select ${COLUMNS} from public.shop_customer_accounts where tenant_id=$1 and shop_id=$2 and normalized_email=$3`,[tenantId,shopId,user.email])).rows[0];if(existing)return{customer:account(existing),created:false};const created=(await c.query<Row>(`insert into public.shop_customer_accounts(tenant_id,shop_id,email,normalized_email,full_name,status,created_by_magrit_user_id) values($1,$2,$3,$3,$4,'delegated_only',$5) returning ${COLUMNS}`,[tenantId,shopId,user.email,user.name?.trim()||user.email.split('@')[0]||'Client',actor])).rows[0]!;return{customer:account(created),created:true};});}
  findByCustomerContactId(actor:UserId,tenantId:string,shopId:string,contactId:string):Promise<ShopCustomerAccount|null>{return this.read(actor,tenantId,async c=>{await shop(c,tenantId,shopId);return maybe((await c.query<Row>(`select ${COLUMNS} from public.shop_customer_accounts where tenant_id=$1 and shop_id=$2 and customer_contact_id=$3`,[tenantId,shopId,contactId])).rows[0]);});}
  listByCustomerContactId(actor:UserId,tenantId:string,contactId:string):Promise<ShopCustomerAccount[]>{return this.read(actor,tenantId,async c=>(await c.query<Row>(`select ${COLUMNS} from public.shop_customer_accounts where tenant_id=$1 and customer_contact_id=$2 order by created_at desc,id`,[tenantId,contactId])).rows.map(account));}
  linkCustomerContact(actor:UserId,tenantId:string,accountId:string,contactId:string):Promise<ShopCustomerAccount>{return this.write(actor,tenantId,'can_manage_shop_customers',async c=>{const current=(await c.query<{status:string}>(`select status from public.shop_customer_accounts where tenant_id=$1 and id=$2`,[tenantId,accountId])).rows[0];if(!current)throw reject('account_not_found','Compte boutique introuvable.');const row=(await c.query<Row>(`update public.shop_customer_accounts set customer_contact_id=$3,status=case when status='active' then status else 'invited' end,suspended_at=case when status='active' then suspended_at else null end where tenant_id=$1 and id=$2 returning ${COLUMNS}`,[tenantId,accountId,contactId])).rows[0]!;return account(row);});}
  revokeCustomerContactAccess(actor:UserId,tenantId:string,shopId:string,contactId:string):Promise<void>{return this.write(actor,tenantId,'can_manage_shop_customers',async c=>{await shop(c,tenantId,shopId);const result=await c.query(`update public.shop_customer_accounts set customer_contact_id=null,status='suspended',suspended_at=clock_timestamp() where tenant_id=$1 and shop_id=$2 and customer_contact_id=$3`,[tenantId,shopId,contactId]);if(result.rowCount!==1)throw reject('account_not_found','Aucun accès boutique ouvert pour cet interlocuteur.');});}

  private read<T>(actor:UserId,tenantId:string,fn:(c:PoolClient)=>Promise<T>):Promise<T>{return this.run(actor,tenantId,fn);}
  private write<T>(actor:UserId,tenantId:string,capability:string,fn:(c:PoolClient)=>Promise<T>):Promise<T>{return this.run(actor,tenantId,async c=>{if(!(await c.query<{allowed:boolean}>('select magrit.actor_has_capability($1,$2) allowed',[tenantId,capability])).rows[0]?.allowed)throw reject('permission_denied',`La capacité ${capability} est requise.`);return fn(c);});}
  private async run<T>(actor:UserId,tenantId:string,fn:(c:PoolClient)=>Promise<T>):Promise<T>{try{return await this.tx.run({tenantId:tenantId as TenantId,userId:actor},fn);}catch(error){if(error instanceof ShopCustomerRejectedError)throw error;const e=error as {code?:string;message?:string};if(e.code==='23505')throw reject('duplicate_email','Un compte existe déjà pour cet email ou cet interlocuteur dans cette boutique.');if(e.code==='23503'||e.code==='23514')throw reject('invalid_request',e.message??'Compte boutique invalide.');throw reject('permission_denied',e.message??String(error));}}
}

async function shop(c:PoolClient,tenantId:string,shopId:string){if(!(await c.query('select 1 from public.shops where tenant_id=$1 and id=$2 and deleted_at is null',[tenantId,shopId])).rowCount)throw reject('shop_not_found','Boutique introuvable dans cet espace.');}
function maybe(row:Row|undefined){return row?account(row):null;}
function account(row:Row):ShopCustomerAccount{return shopCustomerAccountSchema.parse({id:String(row['id']),shopId:String(row['shop_id']),email:String(row['email']),normalizedEmail:String(row['normalized_email']),fullName:String(row['full_name']),authSubjectId:row['auth_subject_id']===null?null:String(row['auth_subject_id']),status:row['status'],createdByMagritUserId:row['created_by_magrit_user_id']===null?null:String(row['created_by_magrit_user_id']),customerContactId:row['customer_contact_id']===null?null:String(row['customer_contact_id']),createdAt:iso(row['created_at']),activatedAt:nullableIso(row['activated_at']),suspendedAt:nullableIso(row['suspended_at'])});}
function iso(value:unknown){return value instanceof Date?value.toISOString():new Date(String(value)).toISOString();}
function nullableIso(value:unknown){return value===null?null:iso(value);}
function reject(code:ConstructorParameters<typeof ShopCustomerRejectedError>[0],message:string){return new ShopCustomerRejectedError(code,message);}
