import { test, expect } from '@playwright/test';
import { loginAs } from './_helpers/auth';
import { TEST_IDS } from '../../src/shared/presentation/testIds';

// Exécuté uniquement par scripts/test-fixed-price-purchase.mjs sur sa base jetable.
test.skip(process.env.MAGRIT_FIXED_RECIPE !== '1', 'Recette isolée requise.');
test('création back-office, publication, prix margé, panier et commande persistée', async ({ page }) => {
  test.setTimeout(90_000);
  const tenant = '20000000-0000-4000-8000-000000000001';
  const library = process.env.MAGRIT_RECIPE_LIBRARY_ID!;
  const shop = process.env.MAGRIT_RECIPE_SHOP_ID!;
  const providerCalls: string[] = [];
  page.on('request', request => {
    if (/\/clariprint\/quote|hopstudio.*quote/.test(request.url())) providerCalls.push(request.url());
  });
  await loginAs(page, 'developer@magrit.local', 'magrit-development-only');
  await page.goto(`/t/magrit-development/dashboard/library/${library}`);
  await page.getByRole('button', { name: 'Ajouter un produit à prix fixe' }).click();
  await page.getByLabel('Nom du produit').fill('Article unitaire recette');
  await page.getByLabel('Coût unitaire HT (€)').fill('100');
  const creation = page.waitForResponse(response => response.request().method() === 'POST' && response.url().includes('/library-products'));
  await page.getByRole('button', { name: 'Créer le produit', exact: true }).click();
  expect((await creation).status()).toBe(201);
  await expect(page.getByRole('dialog')).toBeHidden();
  await expect(page.getByText('Article unitaire recette', { exact: true })).toBeVisible();
  await page.goto(`/t/magrit-development/dashboard/shops/${shop}`);
  await page.getByLabel(/Articles fixes recette/).check();
  const publication = page.waitForResponse(response => response.request().method() === 'PATCH' && response.url().endsWith(`/shops/${shop}`));
  await page.getByRole('button', { name: 'Enregistrer les modifications' }).click();
  expect((await publication).ok()).toBe(true);
  await page.goto('/shop/recette-prix-fixe/catalog');
  const search = page.getByRole('combobox', { name: 'Rechercher un produit ou une catégorie' }).first();
  await search.fill('Article unitaire recette');
  await search.press('Enter');
  await expect(page).toHaveURL(/\/p\//);
  await expect(page.getByText(/125[,.]00/).first()).toBeVisible();
  await expect(page.getByRole('button', { name: 'Configurer', exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: 'Ajouter au panier', exact: true }).click();
  await page.getByRole('button', { name: /^Panier/ }).click();
  await page.getByRole('button', { name: 'Augmenter', exact: true }).click();
  await page.getByRole('button', { name: 'Augmenter', exact: true }).click();
  await expect(page.getByText('3 unités', { exact: true })).toBeVisible();
  await page.screenshot({ path: test.info().outputPath('panier-prix-fixe.png') });
  await page.getByTestId(TEST_IDS.shop.checkoutBtn).click();
  await page.getByTestId(TEST_IDS.shop.checkoutEmailInput).fill('acheteur@example.invalid');
  await page.getByTestId(TEST_IDS.shop.checkoutPasswordInput).fill('recette-fixed-only');
  await page.getByTestId(TEST_IDS.shop.checkoutAuthBtn).click();
  await expect(page.getByRole('heading', { name: 'Récapitulatif de votre commande' })).toBeVisible();
  const persisted = page.waitForResponse(response => response.request().method() === 'POST' && response.url().endsWith('/api/v1/orders'));
  await page.getByTestId(TEST_IDS.shop.checkoutSubmitBtn).click();
  const order = await (await persisted).json();
  expect(order.totalHt).toBe('375.00');
  await expect(page.getByTestId(TEST_IDS.shop.thankYouPage)).toContainText('Commande transmise');
  const rows = await page.request.get(`/api/v1/tenants/${tenant}/orders`);
  expect(rows.ok()).toBe(true);
  expect(JSON.stringify(await rows.json())).toContain(order.orderId);
  await page.screenshot({ path: test.info().outputPath('commande-prix-fixe.png') });
  expect(providerCalls).toEqual([]);
});
