/** Entree publique des contrats transverses de l API Gestion commerciale. */
export {
  anySuccessEnvelopeSchema,
  apiEnumTokenSchema,
  auditSchema,
  CONTRACT_ALIGNMENT,
  currencySchema,
  DEFAULT_PAGE_SIZE,
  ETAG_HEADER,
  EVENT_NAME_HEADER,
  EVENT_SIGNATURE_HEADER,
  eventEnvelopeSchema,
  eventNameSchema,
  eventSignatureSchema,
  GESCOM_API_BASE_PATH,
  IDEMPOTENCY_KEY_HEADER,
  IDEMPOTENCY_REPLAYED_HEADER,
  idempotencyKeySchema,
  IF_MATCH_HEADER,
  JSON_MEDIA_TYPE,
  MAX_PAGE_SIZE,
  metaSchema,
  moneySchema,
  OUTBOX_EVENT_NAMES,
  PAGE_CURSOR_PARAM,
  PAGE_SIZE_PARAM,
  pageParamsSchema,
  PROBLEM_MEDIA_TYPE,
  problemCodeSchema,
  problemFieldErrorSchema,
  problemSchema,
  rateSchema,
  REQUEST_ID_HEADER,
  SERVICE_KEY_HEADER,
  successEnvelopeSchema,
  TENANT_SELECTION_HEADER,
  timestampSchema,
  uuidSchema,
} from './contracts.ts';

export {
  checkResourcePath,
  isResourcePosition,
  PATH_PARAM_SEGMENT,
  RESOURCE_SEGMENT,
  TENANT_ADDRESSING_TOKENS,
} from './path-rules.ts';
export type { PathViolation } from './path-rules.ts';

export type {
  AuditDto,
  EventEnvelopeDto,
  EventNameDto,
  MetaDto,
  MoneyDto,
  PageParamsDto,
  ProblemDto,
  ProblemFieldErrorDto,
  RateDto,
  SuccessEnvelopeDto,
  TimestampDto,
  UuidDto,
} from './contracts.ts';
