import { randomUUID } from 'node:crypto';
import { afterAll,beforeAll,describe,expect,it } from 'vitest';
import type { Pool } from 'pg';
import { createPostgresPool } from '../../src/adapters/postgres/pool.ts';
import { PostgresTransactionRunner } from '../../src/adapters/postgres/transaction-runner.ts';
import { PostgresStorefrontActivationGateway } from '../../src/adapters/postgres/storefront-activation-gateway.ts';
import { PostgresStorefrontAuthenticationGateway } from '../../src/adapters/postgres/storefront-authentication-gateway.ts';
import { PostgresStorefrontPasswordRecoveryGateway } from '../../src/adapters/postgres/storefront-password-recovery-gateway.ts';
import type { TenantId,UserId } from '../../src/kernel/ids/index.ts';

const enabled=process.env['MAGRIT_POSTGRES_INTEGRATION']==='1';const describeIntegration=enabled?describe:describe.skip;
describeIntegration('Activation et recovery storefront — PostgreSQL reel',()=>{
  let pool:Pool,activation:PostgresStorefrontActivationGateway,recovery:PostgresStorefrontPasswordRecoveryGateway,authentication:PostgresStorefrontAuthenticationGateway;
  const tenantId=randomUUID() as TenantId,ownerId=randomUUID() as UserId,shopId=randomUUID(),accountId=randomUUID(),slug=`activation-${randomUUID()}`;
  beforeAll(async()=>{pool=createPostgresPool();const tx=new PostgresTransactionRunner(pool,'magrit_api');activation=new PostgresStorefrontActivationGateway(tx);recovery=new PostgresStorefrontPasswordRecoveryGateway(tx);authentication=new PostgresStorefrontAuthenticationGateway(tx);await pool.query('insert into public.app_users(id,email_normalized) values($1,$2)',[ownerId,`owner-${ownerId}@example.invalid`]);await pool.query(`insert into public.tenants(id,slug,name) values($1,$2,'Activation storefront')`,[tenantId,`activation-${tenantId}`]);await pool.query(`insert into public.tenant_members(tenant_id,user_id,role) values($1,$2,'owner')`,[tenantId,ownerId]);await pool.query(`insert into public.shops(id,tenant_id,owner_user_id,slug,name) values($1,$2,$3,$4,'Boutique activation')`,[shopId,tenantId,ownerId,slug]);await pool.query(`insert into public.shop_customer_accounts(id,tenant_id,shop_id,email,normalized_email,full_name,status,created_by_magrit_user_id) values($1,$2,$3,'invitee@example.test','invitee@example.test','Invitée','invited',$4)`,[accountId,tenantId,shopId,ownerId]);});
  afterAll(async()=>{if(!pool)return;await pool.query('delete from public.tenants where id=$1',[tenantId]);await pool.query('delete from public.app_users where id=$1',[ownerId]);await pool.end();});
  it('emet et consomme une activation a usage unique puis ouvre une session',async()=>{const issued=await activation.issue(ownerId,tenantId,shopId,accountId,3600);expect(issued).toMatchObject({customerEmail:'invitee@example.test',shopSlug:slug});const rawSearch=await pool.query('select 1 from private.shop_customer_activation_tokens where encode(token_hash,\'hex\')=$1',[issued!.token]);expect(rawSearch.rowCount).toBe(0);const activated=await activation.activate(issued!.token,'activated-password');expect(activated?.session).toMatchObject({customer:{id:accountId,status:'active'}});expect(await activation.activate(issued!.token,'another-password')).toBeNull();expect((await authentication.authenticate(slug,'invitee@example.test','activated-password'))?.session.customer.id).toBe(accountId);});
  it('limite les emissions recovery et revoque les sessions au reset',async()=>{const activeSession=await authentication.authenticate(slug,'invitee@example.test','activated-password');const issued=await recovery.issue(slug,'invitee@example.test');expect(issued).toMatchObject({customerEmail:'invitee@example.test'});expect(await recovery.issue(slug,'invitee@example.test')).toBeNull();expect(await recovery.reset(issued!.token,'reset-password')).toBe(true);expect(await recovery.reset(issued!.token,'other-password')).toBe(false);expect(await authentication.resolve(activeSession!.opaqueToken)).toBeNull();expect(await authentication.authenticate(slug,'invitee@example.test','activated-password')).toBeNull();expect((await authentication.authenticate(slug,'invitee@example.test','reset-password'))?.session.customer.id).toBe(accountId);});
});
